### ISSUE TITLE
CocoaPods integration

### ISSUE THREAD

**Issue by cleberhenriques** [pixelogik/ColorCube#10]
Hello,

First: Congrats for the work you've done! This is a great feature. I'll only suggest that you could create a CocoaPods for this library... this makes things a lot easier to integrate :) 

Thanks.

**Comment by cleberhenriques** [comment]
Sorry, i haven't seen that already existed an issue for this.

**Comment by pixelogik** [comment]
No problem :) Thanks for caring.
