### ISSUE TITLE
Python: Order by brightness

### ISSUE THREAD

**Issue by mickeyl** [pixelogik/ColorCube#13]
Thanks for this great implementation! Could you give a hint how to implement the missing sort-by-brightness functionality in the Python version? Cheers, :M:

**Comment by pixelogik** [comment]
In the iOS version the brightness of each histogram cell is set to the maximum color component over all pixels in that cell. Which is not really nice. Instead we should use something like luminance (https://en.wikipedia.org/wiki/Luma_%28video%29). So each cell gets as luminance the maximum luminance over all pixels in that cell (or the luminance of the cell average color - the difference should not be too big anyway). Then sort the resulting local maximas by the luminance in the corresponding cells.
