### ISSUE TITLE
Certain method always produces error

### ISSUE THREAD

**Issue by inorganik** [pixelogik/ColorCube#2]
Hi,

First of all, this is a rad library! Thanks! 

I'm finding that whenever I use this particular method, I get an error that crashes the app:

`- (NSArray *)extractColorsFromImage:(UIImage *)image flags:(NSUInteger)flags avoidColor:(UIColor*)avoidColor;`

This happens avoiding either black or white. The error:

`-[UIDeviceRGBColor red]: unrecognized selector sent to instance 0x7f86c8eab8e0`

Outside of this small issue, I've found this lib works perfectly.

**Comment by pixelogik** [comment]
Hi there, 

thanks for the props! And thanks for the report. I will check that asap. 

Cheers

**Comment by pixelogik** [comment]
Was a one-line fix fortunately :) Thanks again for spotting it!
