### ISSUE TITLE
javascript port

### ISSUE THREAD

**Issue by amonks** [pixelogik/ColorCube#7]
Ole!

I like your algorithm more than any of the existing in-browser tools for color extraction, so I made a [javascript port](https://github.com/amonks/colorcube-js).

Great work on ColorCube! The port would have been a lot harder without your super-clean code. :revolving_hearts:

**Comment by pixelogik** [comment]
Hey Andrew,

thanks for the flowers and references! 

Nice job on the port! Yeah, I always try to make the code self-explanatory, helps also myself when jumping on the project a year later. 

Cheers
